# spell-checker: ignore yamllint chmod
---
# yamllint disable rule:line-length
name: pre-commit

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install terraform-docs
        run: |
          sudo curl -sL --output - https://github.com/terraform-docs/terraform-docs/releases/download/v0.16.0/terraform-docs-v0.16.0-linux-amd64.tar.gz | tar xzf - -C /usr/local/bin
          sudo chmod 0755 /usr/local/bin/terraform-docs
      - uses: actions/setup-python@v2
      - uses: actions/setup-go@v2
      - uses: pre-commit/action@v2.0.0
